config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  devise_for :users
  resources :person, only: [:create, :new, :index, :destroy, :edit, :update]
  resources :category, only: [:destroy]
  resources :money_transaction, only: [:destroy]
  resources :note , only: [:destroy]
  post '/person/new', to: 'person#create'

  post '/person/:id/edit', to: 'person#update'

  root 'home#index'

  get '/person/:id/categories', to: 'person#categories_index', as: 'person_categories_index'

  match '/404', to: 'errors#not_found', via: :all

  get '/categories', to: 'category#index'

  get '/categories/:id/edit', to: 'category#edit', as: 'edit_category'
  post '/categories/:id/edit', to: 'category#update'

  get '/categories/new', to: 'category#new'
  post '/categories/new', to: 'category#create'

  get '/transactions', to: 'money_transaction#index'

  get '/transactions/new', to: 'money_transaction#new'
  post '/transactions/new', to: 'money_transaction#create'

  get '/transactions/:id/edit', to: 'money_transaction#edit', as: 'edit_transaction'
  post '/transactions/:id/edit', to: 'money_transaction#update'

  get '/categories/:id', to: 'category#info', as: 'category_info'
  post '/categories/:id', to: 'category#info', as: 'category_info_post'

  get '/note/:id/show', to: 'note#show', as: 'show_note'
  get '/note/:id/edit', to: 'note#edit', as: 'edit_note'
  post '/note/:id/edit', to: 'note#update'
  get '/transactions/important', to: 'money_transaction#important', as: 'important_index'
  get '/information', to: 'charts#index', as: 'information_page'
  post '/information', to: 'charts#index', as: 'information_page_post'
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :person_categories
  has_many :people, through: :person_categories, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3, maximum: 10 }
  validates :people, presence: true

  def destroy
    people.each do |person|
      return false if person.categories.count == 1
    end

    super
  end

  def debit_to_string
    debit ? 'Debit' : 'Credit'
  end
end

app/controllers/category_controller.rb
# frozen_string_literal: true

class CategoryController < ApplicationController
  before_action :category_find, only: %i[edit update destroy]
  before_action :require_signed_user, only: %i[index edit update destroy new info]
  before_action :require_same_signed_user, only: %i[edit update destroy info]

  def new
    @category = Category.new
  end

  def edit; end

  def update
    prms = params[:category][:id].reject(&:empty?)
    if !prms.empty? && @category.update(category_params)
      destroy_person_categories(@category, prms)
      add_person_to_category(@category, prms)
      flash[:notice] = 'Category updated'
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def create
    @category = Category.new(category_params)
    params[:category][:id].each { |id| @category.people << Person.find(id) if id.present? }
    if @category.save
      flash[:notice] = 'Category created successfully'
      redirect_to categories_path
    else
      render :new
    end
  end

  def index
    @categories = current_user.people.collect(&:categories).flatten.uniq
  end

  def destroy
    if @category.destroy
      flash[:notice] = 'Category deleted successfully'
    else
      flash[:alert] = 'For one of your persons this category is the only one. Last category could not be deleted'
    end
    redirect_to categories_path
  end

  # rubocop:disable Metrics/AbcSize
  def info
    if params_date_validator(params)
      @start_date = Date.today.beginning_of_month
      @end_date = date_to_datetime(Date.today)
    else
      @start_date = Date.parse(params[:money_transaction][:start_date])
      @end_date = date_to_datetime(Date.parse(params[:money_transaction][:end_date]))
    end
    @category = Category.find(params[:id])
    @transactions = transaction_selector(pc_of_category(@category, @start_date, @end_date), params)
    @sum_amount_value = @transactions.inject(0) { |sum, t| sum + t.amount_value }
  end

  private

  def transaction_selector(person_category, params)
    trs = MoneyTransaction.where(person_category_id: person_category)
    trs = trs.where.not(note: nil) if !params[:with_note].nil? && (params[:with_note].values[0] == '1')
    trs.where(important: true) if !params[:important].nil? && (params[:important].values[0] == '1')
    trs
  end

  # rubocop:enable Metrics/AbcSize

  def date_to_datetime(date)
    date.to_datetime.end_of_day
  end

  def date?(date)
    date =~ /\d{4}-\d{2}-\d{2}/
  end

  def pc_of_category(category, start_date, end_date)
    PersonCategory.where(category_id: category, created_at: start_date..end_date)
  end

  def params_date_validator(params)
    params[:money_transaction].nil? || params[:money_transaction][:start_date].nil? ||
      params[:money_transaction][:end_date].nil? || !date?(params[:money_transaction][:start_date]) ||
      !date?(params[:money_transaction][:end_date])
  end

  def destroy_person_categories(category, non_empty_params)
    PersonCategory.where(category_id: category.id).each do |person_category|
      person_category.destroy if non_empty_params.exclude?(person_category.person_id.to_s)
    end
  end

  def add_person_to_category(category, non_empty_params)
    non_empty_params.each do |person_id|
      category.people << Person.find(person_id) unless category.people.include?(Person.find(person_id))
    end
  end

  def category_params
    params.require(:category).permit(:title, :debit)
  end

  def category_find
    @category = Category.find(params[:id])
  end

  def require_signed_user
    return if user_signed_in?

    flash[:alert] = 'You must be signed in to do that'
    redirect_to root_path
  end

  def require_same_signed_user
    category = Category.find(params[:id])
    return if current_user == category.people.first.user

    flash[:alert] = 'You must be the owner to do this.'
    redirect_to root_path
  end
end

app/helpers/category_helper.rb
# frozen_string_literal: true

module CategoryHelper
  def can_be_deleted?(category)
    category.people.each do |person|
      return false if person.categories.count == 1
    end
    true
  end
end

app/views/category/edit.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular plus icon"></i>
  Edit category
</h2>


<%= form_for :category do |f| %>
  <div class="ui segment inverted">
    <%= render "devise/shared/error_messages", resource:  @category %>
    <div class="ui form inverted">
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, placeholder: 'title' %>
      </div>
      <div class="field">
        <%= f.label 'Debit' %>
        <%= f.check_box :debit, placeholder: 'Debit' %>
      </div>
      <div class="field">
        <%= f.label 'List of person' %>
        <%= f.collection_select(:id, current_user.people.order(:name),:id,:name, {:prompt => nil}, {:multiple => true}) %>
      </div>
      <%= f.submit "Create category", class: 'ui button'%>
    </div>
  </div>
<% end %>

app/views/category/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular file alternate outline icon"></i>
  Your categories
  <div><%= link_to 'Create new category', categories_new_path, class: 'ui red basic button centered' %></div>

</h2>
<% @categories.each do |category| %>


  <div class="ui centered card">
    <div class="content">

      <%= link_to category.title + ' ['+category.debit_to_string+']', '/categories/'+category.id.to_s, class: 'center aligned header' %>

      <div class="center aligned description">
        <!--I used the uniq method because the same category can be debit or credit-->
        <p>Count of persons: <%= category.person_ids.uniq.count %></p>
        <p>Total amount: N/A</p>
      </div>
    </div>

    <div class="extra content">
      <div class="center aligned author">
        <%= link_to 'Edit', edit_category_path(category), class: 'ui blue basic button' %>
        <%= link_to 'Delete', category_path(category), method: :delete, class: can_be_deleted?(category) ? 'ui red basic button' : 'ui red basic button disabled', data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  </div>






<% end %>

app/views/category/info.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular calendar alternate icon"></i>
  Transactions of <%= @category.title %> between
  <%= form_for :money_transaction do |f| %>
    <div class="m-top-15">
      <%= f.date_field :start_date, value: @start_date %>
      and
      <%= f.date_field :end_date, value: @end_date.to_date %>
    </div>

    <div>Only with note: <%=check_box :with_note, type:'checkbox' %></div>
    <div>Only important note: <%=check_box :important, type:'checkbox' %></div>

    <div class="m-top-15">
      <%= f.submit "Search", class: 'ui blue basic button' %>
    </div>
  <% end %>

</h2>

<h2 class="ui center aligned icon header">
  amount by category <%= @category.title %>  is <p class="transaction-value"><%= @sum_amount_value %></p>
  <div class="m-top-15">
    List of transactions
  </div>
</h2>


<% @transactions.each do |transaction| %>

  <div class="ui centered card">
    <div class="content">
      <div class="center aligned header"><%= transaction.person_category.person.title %></div>

      <div class="center aligned description">
        <p>Operation type: <%= transaction.person_category.category.debit ? 'Debit' : 'Credit' %></p>
        <p>Category: <%= transaction.person_category.category.title %></p>
        <p>Amount value: <%= transaction.amount_value %></p>

        <% unless transaction.note.nil? %>

          <div class="ui centered card">
            <div class="content">
              <div class="center aligned header">Note</div>
              <div class="center aligned description">
                <p class="center aligned note-body" style="color: <%= transaction.note.color %>"><%= transaction.note.body %></p>
                <%= link_to 'Edit', edit_note_path(transaction.note), class: 'ui blue basic mini button' %>
                <%= link_to 'Delete', note_path(transaction.note), method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui red basic mini button' %>
              </div>
            </div>
          </div>
        <% else %>
          <p>Note: not exist</p>
        <% end %>
      </div>
    </div>

    <div class="extra content">
      <div class="center aligned author">
        <%= link_to 'Edit', edit_transaction_path(transaction), class: 'ui blue basic button' %>
        <%= link_to 'Delete', money_transaction_path(transaction), method: :delete, class: 'ui red basic button ', data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  </div>
<% end %>

app/views/category/new.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular plus icon"></i>
  Create category
</h2>


<%= form_for :category do |f| %>
  <div class="ui segment inverted">
    <%= render "devise/shared/error_messages", resource:  @category %>
    <div class="ui form inverted">
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, placeholder: 'title' %>
      </div>
      <div class="field">
        <%= f.label 'Debit' %>
        <%= f.check_box :debit, placeholder: 'Debit' %>
      </div>
      <div class="field">
        <%= f.label 'List of person' %>
        <%= f.collection_select(:id, current_user.people.order(:name),:id,:name, {:prompt => nil}, {:multiple => true}) %>
      </div>
      <%= f.submit "Create category", class: 'ui button'%>
    </div>
  </div>
<% end %>