config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  devise_for :users
  resources :person, only: [:create, :new, :index, :destroy, :edit, :update]
  resources :category, only: [:destroy]
  resources :money_transaction, only: [:destroy]
  resources :note , only: [:destroy]
  post '/person/new', to: 'person#create'

  post '/person/:id/edit', to: 'person#update'

  root 'home#index'

  get '/person/:id/categories', to: 'person#categories_index', as: 'person_categories_index'

  match '/404', to: 'errors#not_found', via: :all

  get '/categories', to: 'category#index'

  get '/categories/:id/edit', to: 'category#edit', as: 'edit_category'
  post '/categories/:id/edit', to: 'category#update'

  get '/categories/new', to: 'category#new'
  post '/categories/new', to: 'category#create'

  get '/transactions', to: 'money_transaction#index'

  get '/transactions/new', to: 'money_transaction#new'
  post '/transactions/new', to: 'money_transaction#create'

  get '/transactions/:id/edit', to: 'money_transaction#edit', as: 'edit_transaction'
  post '/transactions/:id/edit', to: 'money_transaction#update'

  get '/categories/:id', to: 'category#info', as: 'category_info'
  post '/categories/:id', to: 'category#info', as: 'category_info_post'

  get '/note/:id/show', to: 'note#show', as: 'show_note'
  get '/note/:id/edit', to: 'note#edit', as: 'edit_note'
  post '/note/:id/edit', to: 'note#update'
  get '/transactions/important', to: 'money_transaction#important', as: 'important_index'
  get '/information', to: 'charts#index', as: 'information_page'
  post '/information', to: 'charts#index', as: 'information_page_post'
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  belongs_to :user
  has_many :person_categories
  has_many :categories, through: :person_categories, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3, maximum: 30 }
  validates :name, presence: true, length: { minimum: 3, maximum: 30 }
  validates :lastname, presence: true, length: { minimum: 5, maximum: 30 }
  after_create :create_category

  def create_category
    category = Category.new(title: 'change me', debit: true)
    category.people << self
    category.save
  end

  def destroy
    return false if user.people.count == 1

    super
  end
end

app/controllers/person_controller.rb
# frozen_string_literal: true

class PersonController < ApplicationController
  before_action :require_signed_user, only: %i[index destroy create new edit update]
  before_action :require_same_signed_user, only: %i[destroy edit update]
  before_action :find_person, only: %i[edit update destroy]

  def index
    @persons = current_user.people
  end

  def new
    @person = Person.new
  end

  def edit; end

  def update
    if @person.update(person_params)
      flash[:notice] = 'Person updated successfully'
      redirect_to person_index_path
    else
      render :edit
    end
  end

  def create
    @person = Person.new(person_params)
    @person.user = current_user
    if @person.save
      flash[:notice] = 'Person was successfully created.'
      redirect_to person_index_path
    else
      render :new
    end
  end

  def categories_index
    @categories = find_person.categories
  end

  def destroy
    if @person.destroy
      flash[:notice] = 'Person deleted successfully'
    else
      flash[:alert] = 'Last person could not be deleted'
    end

    redirect_to person_index_path
  end

  private

  def require_signed_user
    return if user_signed_in?

    flash[:alert] = 'You must be signed in to do that'
    redirect_to root_path
  end

  def find_person
    @person = Person.find(params[:id])
  end

  def require_same_signed_user
    person = Person.find(params[:id])
    return if current_user == person.user

    flash[:alert] = 'You can only delete your own person'
    redirect_to root_path
  end

  def person_params
    params.require(:person).permit(:title, :name, :lastname)
  end
end

app/helpers/person_helper.rb
# frozen_string_literal: true

module PersonHelper
end

app/views/person/categories_index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular file alternate outline icon"></i>
  Categories of <%= @person.name %>
  <div><%= link_to 'Create new category', categories_new_path, class: 'ui red basic button centered' %></div>

</h2>
<% @categories.each do |category| %>


  <div class="ui centered card">
    <div class="content">
      <div class="center aligned header"><%= category.title %> [<%= category.debit ? 'Debit' : 'Credit' %>]</div>

      <div class="center aligned description">
        <p>Total amount: N/A</p>
      </div>
    </div>

    <div class="extra content">
      <div class="center aligned author">
        <!-- TODO: Fix path -->
        <%=link_to 'Edit',edit_category_path(category) ,class:'ui blue basic button' %>
        <%= link_to 'Delete', category_path(category), method: :delete, class: can_be_deleted?(category) ? 'ui red basic button': 'ui red basic button disabled', data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  </div>

<% end %>

app/views/person/edit.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular edit icon"></i>
  Edit person
</h2>


<%= form_for :person, url: edit_person_path do |f|  %>

  <div class="ui segment inverted">
    <%= render "devise/shared/error_messages", resource: @person %>
    <div class="ui form inverted">
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, placeholder: 'title' %>
      </div>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: 'name' %>
      </div>
      <div class="field">
        <%= f.label :lastname %>
        <%= f.text_field :lastname, placeholder: 'lastname' %>
      </div>
      <%= f.submit "Edit person", class: 'ui button'%>
    </div>
  </div>
<% end %>

app/views/person/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular id card outline icon"></i>
  Your persons
  <div><%= link_to 'Create new Person', new_person_path, class: 'ui red basic button centered' %></div>
</h2>


<% @persons.each do |person| %>
  <div class="ui centered card">
    <div class="content">
      <div class="center aligned header"><%= person.title %></div>
      <div class="center aligned description">
        <p>Name: <%= person.name %></p>
      </div>
      <div class="center aligned description">
        <p>Lastname: <%= person.lastname %></p>
      </div>
    </div>
    <div class="extra content">
      <div class="center aligned author">
        <%=link_to 'Edit', edit_person_path(person) ,class:'ui blue basic button' %>
        <%= link_to 'Delete', person_path(person), method: :delete, class: current_user.people.count > 1 ? 'ui red basic button' : 'ui red basic button disabled', data: { confirm: 'Are you sure?' } %>

        <!-- TODO: fix path!!! -->
        <%=link_to 'Categories', person_categories_index_path(person) ,class:'ui teal basic button categories-btn' %>

        <% unless current_user.people.count > 1 %>
          <div class="ui negative message">
            <div class="header">
              You can't delete the last person
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/person/new.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular user plus icon"></i>
  Create person
</h2>


<%= form_for :person do |f| %>

  <div class="ui segment inverted">
    <%= render "devise/shared/error_messages", resource: @person %>
  <div class="ui form inverted">
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: 'title' %>
    </div>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: 'name' %>
    </div>
    <div class="field">
      <%= f.label :lastname %>
      <%= f.text_field :lastname, placeholder: 'lastname' %>
    </div>
    <%= f.submit "Create person", class: 'ui button'%>
  </div>
</div>
<% end %>