config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  devise_for :users
  resources :person, only: [:create, :new, :index, :destroy, :edit, :update]
  resources :category, only: [:destroy]
  resources :money_transaction, only: [:destroy]
  resources :note , only: [:destroy]
  post '/person/new', to: 'person#create'

  post '/person/:id/edit', to: 'person#update'

  root 'home#index'

  get '/person/:id/categories', to: 'person#categories_index', as: 'person_categories_index'

  match '/404', to: 'errors#not_found', via: :all

  get '/categories', to: 'category#index'

  get '/categories/:id/edit', to: 'category#edit', as: 'edit_category'
  post '/categories/:id/edit', to: 'category#update'

  get '/categories/new', to: 'category#new'
  post '/categories/new', to: 'category#create'

  get '/transactions', to: 'money_transaction#index'

  get '/transactions/new', to: 'money_transaction#new'
  post '/transactions/new', to: 'money_transaction#create'

  get '/transactions/:id/edit', to: 'money_transaction#edit', as: 'edit_transaction'
  post '/transactions/:id/edit', to: 'money_transaction#update'

  get '/categories/:id', to: 'category#info', as: 'category_info'
  post '/categories/:id', to: 'category#info', as: 'category_info_post'

  get '/note/:id/show', to: 'note#show', as: 'show_note'
  get '/note/:id/edit', to: 'note#edit', as: 'edit_note'
  post '/note/:id/edit', to: 'note#update'
  get '/transactions/important', to: 'money_transaction#important', as: 'important_index'
  get '/information', to: 'charts#index', as: 'information_page'
  post '/information', to: 'charts#index', as: 'information_page_post'
end

app/controllers/money_transaction_controller.rb
# frozen_string_literal: true

class MoneyTransactionController < ApplicationController
  before_action :money_transaction_find, only: %i[edit update destroy]
  before_action :require_signed_user, only: %i[new create edit update destroy index important]
  before_action :require_same_signed_user, only: %i[edit update destroy]

  def index
    current_user_person_categories = PersonCategory.where(person_id: current_user.people)
    @money_transactions = MoneyTransaction.where(person_category_id: current_user_person_categories)
  end

  def new
    @money_transaction = MoneyTransaction.new
  end

  def edit; end

  def update
    if @money_transaction.update_attributes(money_transaction_params)
      flash[:notice] = 'Money transaction was successfully updated.'
      redirect_to transactions_path
    else
      render 'edit'
    end
  end

  def important
    current_user_person_categories = PersonCategory.where(person_id: current_user.people)
    money_transactions = MoneyTransaction.where(person_category_id: current_user_person_categories)
    @money_transactions = money_transactions.where(important: true)
  end

  def create
    @money_transaction = MoneyTransaction.new(money_transaction_params)
    add_note(@money_transaction, params)
    if @money_transaction.save
      flash[:notice] = 'Money transaction was successfully created.'
      redirect_to transactions_path
    else
      render :new
    end
  end

  def destroy
    if @money_transaction.destroy
      flash[:notice] = 'Money transaction was successfully deleted.'
    else
      flash[:alert] = 'Money transaction was not deleted.'
    end
    redirect_to transactions_path
  end

  private

  def add_note(transaction, params)
    return if params[:note_required].nil?

    note = Note.new(body: params[:note_body].values[0], color: params[:color].values[0])
    transaction.note = note if note.valid?
    if note.valid?
      transaction.note = note
    else
      flash[:alert] = 'Note was not added. Saved without note'
    end
  end

  def money_transaction_find
    @money_transaction = MoneyTransaction.find(params[:id])
  end

  def money_transaction_params
    params.require(:money_transaction).permit(:amount_value, :important, :person_category_id)
  end

  def require_signed_user
    return if user_signed_in?

    flash[:alert] = 'You must be signed in to do that'
    redirect_to root_path
  end

  def require_same_signed_user
    mt = MoneyTransaction.find(params[:id])
    return if current_user == mt.person_category.person.user

    flash[:alert] = 'You must be the owner to do this.'
    redirect_to root_path
  end
end

app/helpers/money_transaction_helper.rb
# frozen_string_literal: true

module MoneyTransactionHelper
end

app/views/money_transaction/edit.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular money bill alternate outline icon"></i>
  Update transaction

</h2>

<%= form_for :money_transaction do |f| %>
  <div class="ui segment inverted">
    <%= render "devise/shared/error_messages", resource: @money_transaction %>
    <div class="ui form inverted">
      <div class="field">
        <%= f.label 'Amount' %>
        <%= f.text_field :amount_value, placeholder: 'Amount' %>
      </div>
      <div class="field">
        <div class="important-handler"><%= f.label 'Important status: ' %>
          <%= f.check_box :important, class: 'important-checkbox' %>
        </div>
      </div>
      <div class="field">
        <%= f.label 'Relationship between person and category' %>
        <%= f.collection_select(:person_category_id, PersonCategory.where(person_id: current_user.people), :id, :select_title) %>
      </div>
      <%= f.submit "Update transaction", class: 'ui button' %>
    </div>
  </div>
<% end %>

app/views/money_transaction/important.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular bell outline icon"></i>
  Your important transactions

</h2>


<% @money_transactions.each do |transaction| %>

  <div class="ui centered card">
    <div class="content">
      <div class="center aligned header"><%= transaction.person_category.person.title%></div>

      <div class="center aligned description">
        <p>Operation type: <%=transaction.person_category.category.debit ? 'Debit' : 'Credit' %></p>
        <p>Category: <%=transaction.person_category.category.title %></p>
        <p>Amount value: <%=transaction.amount_value %></p>
      </div>
    </div>

    <div class="extra content">
      <div class="center aligned author">
        <%=link_to 'Edit',edit_transaction_path(transaction) ,class:'ui blue basic button' %>
        <%= link_to 'Delete', money_transaction_path(transaction), method: :delete, class:  'ui red basic button ', data: {confirm: 'Are you sure?'}  %>
      </div>
    </div>
  </div>
<% end %>

app/views/money_transaction/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular money bill alternate outline icon"></i>
  Your transaction
  <div><%= link_to 'Create new transaction', transactions_new_path, class: 'ui red basic button centered' %></div>

</h2>

<% @money_transactions.each do |transaction| %>

  <div class="ui centered card">
    <div class="content">
      <div class="center aligned header"><%= transaction.person_category.person.title%></div>

      <div class="center aligned description">
        <p>Operation type: <%=transaction.person_category.category.debit ? 'Debit' : 'Credit' %></p>
        <p>Category: <%=transaction.person_category.category.title %></p>
        <p>Amount value: <%=transaction.amount_value %></p>
      </div>
    </div>

    <div class="extra content">
      <div class="center aligned author">
        <%=link_to 'Edit',edit_transaction_path(transaction) ,class:'ui blue basic button' %>
        <%= link_to 'Delete', money_transaction_path(transaction), method: :delete, class:  'ui red basic button ', data: {confirm: 'Are you sure?'}  %>
      </div>
    </div>
  </div>
<% end %>

app/views/money_transaction/new.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular money bill alternate outline icon"></i>
  Create transaction

</h2>

<%= form_for :money_transaction do |f| %>
  <div class="ui segment inverted">
    <%= render "devise/shared/error_messages", resource: @money_transaction %>
    <div class="ui form inverted">
      <div class="field">
        <%= f.label 'Amount' %>
        <%= f.text_field :amount_value, placeholder: 'Amount' %>
      </div>
      <div class="field">
        <div class="important-handler">
          <%= f.label 'Important status: ' %>
          <%= f.check_box :important, class: 'important-checkbox' %>
        </div>
      </div>

      <div class="field">
        <div class="important-handler">
          <%= label_tag 'Create note for this transaction: ' %>
          <%= check_box_tag :note_required, 'yes', true, class: 'important-checkbox' %>
        </div>
      </div>


      <div class="note-field">
        <div class="field">
          <label for="">Text of your note:</label>
          <%= text_field :note_body, type: 'text'%>
        </div>
        <div class="note-color field">
          <label class="color-label">Color of your note:</label>
          <%= color_field :color, type: 'color' %>
        </div>
      </div>
      <div class="field">
        <%= f.label 'Relationship between person and category' %>
        <%= f.collection_select(:person_category_id, PersonCategory.where(person_id: current_user.people), :id, :select_title) %>

      </div>
      <%= f.submit "Create transaction", class: 'ui button' %>
    </div>
  </div>
<% end %>