config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  devise_for :users
  resources :person, only: [:create, :new, :index, :destroy, :edit, :update]
  resources :category, only: [:destroy]
  resources :money_transaction, only: [:destroy]
  resources :note , only: [:destroy]
  post '/person/new', to: 'person#create'

  post '/person/:id/edit', to: 'person#update'

  root 'home#index'

  get '/person/:id/categories', to: 'person#categories_index', as: 'person_categories_index'

  match '/404', to: 'errors#not_found', via: :all

  get '/categories', to: 'category#index'

  get '/categories/:id/edit', to: 'category#edit', as: 'edit_category'
  post '/categories/:id/edit', to: 'category#update'

  get '/categories/new', to: 'category#new'
  post '/categories/new', to: 'category#create'

  get '/transactions', to: 'money_transaction#index'

  get '/transactions/new', to: 'money_transaction#new'
  post '/transactions/new', to: 'money_transaction#create'

  get '/transactions/:id/edit', to: 'money_transaction#edit', as: 'edit_transaction'
  post '/transactions/:id/edit', to: 'money_transaction#update'

  get '/categories/:id', to: 'category#info', as: 'category_info'
  post '/categories/:id', to: 'category#info', as: 'category_info_post'

  get '/note/:id/show', to: 'note#show', as: 'show_note'
  get '/note/:id/edit', to: 'note#edit', as: 'edit_note'
  post '/note/:id/edit', to: 'note#update'
  get '/transactions/important', to: 'money_transaction#important', as: 'important_index'
  get '/information', to: 'charts#index', as: 'information_page'
  post '/information', to: 'charts#index', as: 'information_page_post'
end

app/views/layouts/_flash.html.erb
<% if notice %>
<div class="ui success message">
  <i class="close icon"></i>
  <div class="header">
    <%= notice %>
  </div>
</div>
<% end %>
<!-- тут нету else if на случай,
если в будущем будет добавлен функционал, который будет вызывать оба типа алерта  -->
<% if alert %>
<div class="ui negative message">
  <i class="close icon"></i>
  <div class="header">
    <%= alert %>
  </div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="ui inverted vertical footer segment">
  <div class="ui container center aligned">
    Anatoliy Orlovskiy 2021. All Rights are NOT Reserved :)
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="ui huge menu inverted">
  <div class="ui container">
    <%= link_to "Fision", root_path, class:'active item' %>


    <div class="right menu">
      <% if user_signed_in? %>
        <div class="ui dropdown item">

          <%= current_user.email.split('@')[0] %> <i class="dropdown icon"></i>
          <div class="menu">
         <%=link_to 'Persons', person_index_path, class: 'item' %>
            <%=link_to 'Categories', categories_path, class: 'item' %>
            <%=link_to 'Transactions', transactions_path, class: 'item' %>
            <%=link_to 'Important transactions', important_index_path, class: 'item' %>
            <%=link_to 'Information', information_page_path, class: 'item' %>
          </div>
        </div>
        <div class="item">

          <%= link_to 'Log Out', destroy_user_session_path, class: 'ui primary button', method: :delete %>
        </div>
      <% else %>

        <div class="item">

          <%= link_to 'Log In', new_user_session_path, class: 'ui primary button' %>

        </div>
        <div class="item">

          <%= link_to 'Sign Up', new_user_registration_path, class: 'ui primary button' %>

        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ItechartRailsCourse</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= render 'layouts/nav' %>
<div class="ui container p" style="padding-bottom: 100px">



  <%= render 'layouts/flash' %>
  <%= yield %>

</div>

<%= render 'layouts/footer' %>
</body>
</html>